CLPATH="C:\Program Files (x86)\AMD APP SDK\3.0-0-Beta"
CC=gcc
CFLAGS=-Wall -O2 -I$(CLPATH)\include -D_VERBOSE
LDFLAGS=-L$(CLPATH)\lib\x86 -lm -pthread -lOpenCL
SOURCES=approx.c database.c evo.c load_ini.c main.c mwc64x_rng.c opencl_target.c sqlite3.c
EXECUTABLE=glucose.exe

all: $(Release)

Release:
	$(CC) $(CFLAGS) $(SOURCES) -o $(EXECUTABLE) $(LDFLAGS)
	strip $(EXECUTABLE)
Debug:
	$(CC) -g $(CFLAGS) $(SOURCES) -o $(EXECUTABLE) $(LDFLAGS)

clean:
	rm $(EXECUTABLE)
